import type { IndustryId, IndustryPreset, TermKey } from '@/types'

/**
 * Presets por industria/vertical para Sagitta.
 * "Sagitta se adapta al negocio, no el negocio a Sagitta."
 *
 * Cada preset define:
 * 1. Módulos sugeridos habilitados por defecto.
 * 2. Complementos (addons) específicos sugeridos.
 * 3. Diccionario de términos de dominio que adapta el lenguaje de la UI
 *    (ej. en Salud: "Pacientes", en Educación: "Alumnos", en Gastronomía: "Mesas", etc.).
 */
export const INDUSTRY_PRESETS: Record<IndustryId, IndustryPreset> = {
  general: {
    id: 'general',
    label: 'Empresarial General',
    description: 'Configuración estándar versátil para empresas de servicios y comercio.',
    examples: ['Servicios generales', 'Comercio mixto', 'Oficinas de atención'],
    modules: ['reservas', 'servicios', 'profesionales', 'clientes', 'pos', 'finanzas', 'reportes'],
    addons: ['reservas.reprogramacion', 'recepcion.walk_in'],
    terms: {
      cita: 'Cita',
      citas: 'Citas',
      cliente: 'Cliente',
      clientes: 'Clientes',
      profesional: 'Profesional',
      profesionales: 'Profesionales',
      servicio: 'Servicio',
      servicios: 'Servicios',
      recurso: 'Recurso',
      recursos: 'Recursos',
    },
  },

  belleza: {
    id: 'belleza',
    label: 'Belleza y Cuidado Personal',
    description: 'Para salones, barberías, spas, centros de estética y manicura.',
    examples: ['Barberías', 'Peluquerías', 'Spas', 'Uñas & Lash', 'Centros de estética'],
    modules: [
      'reservas',
      'recepcion',
      'servicios',
      'profesionales',
      'recursos',
      'clientes',
      'pos',
      'finanzas',
      'inventario',
      'automatizaciones',
      'reportes',
    ],
    addons: [
      'recepcion.walk_in',
      'recepcion.lista_espera',
      'servicios.paquetes',
      'servicios.membresias',
      'recursos.bloqueos',
      'pos.promociones',
      'pos.gift_cards',
    ],
    terms: {
      cita: 'Cita',
      citas: 'Citas',
      cliente: 'Cliente',
      clientes: 'Clientes',
      profesional: 'Especialista',
      profesionales: 'Especialistas',
      servicio: 'Tratamiento',
      servicios: 'Tratamientos',
      recurso: 'Cabina / Sillón',
      recursos: 'Cabinas y Sillones',
    },
  },

  salud: {
    id: 'salud',
    label: 'Salud y Bienestar Clínico',
    description: 'Para consultorios médicos, clínicas dentales, fisioterapia y psicología.',
    examples: ['Consultorios médicos', 'Odontología', 'Fisioterapia', 'Psicología', 'Nutrición'],
    modules: [
      'reservas',
      'recepcion',
      'servicios',
      'profesionales',
      'recursos',
      'clientes',
      'finanzas',
      'inventario',
      'automatizaciones',
      'reportes',
    ],
    addons: [
      'reservas.reprogramacion',
      'recepcion.lista_espera',
      'recursos.bloqueos',
      'servicios.recetas',
    ],
    terms: {
      cita: 'Consulta',
      citas: 'Consultas',
      cliente: 'Paciente',
      clientes: 'Pacientes',
      profesional: 'Especialista',
      profesionales: 'Especialistas',
      servicio: 'Procedimiento',
      servicios: 'Procedimientos',
      recurso: 'Consultorio',
      recursos: 'Consultorios',
    },
  },

  fitness: {
    id: 'fitness',
    label: 'Fitness, Deportes y Bienestar',
    description: 'Gimnasios, estudios de yoga, pilates, crossfit y entrenadores personales.',
    examples: ['Gimnasios', 'Estudios de Yoga', 'Pilates', 'Crossfit', 'Entrenadores personales'],
    modules: [
      'reservas',
      'recepcion',
      'servicios',
      'profesionales',
      'recursos',
      'clientes',
      'pos',
      'finanzas',
      'inventario',
      'automatizaciones',
      'reportes',
    ],
    addons: [
      'reservas.grupales',
      'recepcion.walk_in',
      'servicios.membresias',
      'servicios.paquetes',
      'recursos.bloqueos',
      'pos.promociones',
    ],
    terms: {
      cita: 'Clase / Sesión',
      citas: 'Clases',
      cliente: 'Miembro / Atleta',
      clientes: 'Miembros',
      profesional: 'Entrenador / Coach',
      profesionales: 'Entrenadores',
      servicio: 'Disciplina / Programa',
      servicios: 'Programas',
      recurso: 'Sala / Cancha',
      recursos: 'Salas y Espacios',
    },
  },

  automotriz: {
    id: 'automotriz',
    label: 'Automotriz y Talleres',
    description: 'Talleres mecánicos, detailing, lavado automotriz y mantenimiento preventivo.',
    examples: ['Talleres mecánicos', 'Detailing', 'Lavado de autos', 'Mantenimiento'],
    modules: [
      'reservas',
      'recepcion',
      'servicios',
      'profesionales',
      'recursos',
      'clientes',
      'pos',
      'finanzas',
      'inventario',
      'reportes',
    ],
    addons: [
      'recepcion.walk_in',
      'recursos.bloqueos',
      'servicios.recetas',
      'finanzas.cotizaciones',
    ],
    terms: {
      cita: 'Orden de Servicio',
      citas: 'Órdenes',
      cliente: 'Cliente / Propietario',
      clientes: 'Clientes',
      profesional: 'Mecánico / Técnico',
      profesionales: 'Técnicos',
      servicio: 'Servicio Mecánico',
      servicios: 'Servicios',
      recurso: 'Bahía / Elevador',
      recursos: 'Bahías y Elevadores',
    },
  },

  educacion: {
    id: 'educacion',
    label: 'Educación, Cursos y Academias',
    description: 'Academias de idiomas, clases de música, arte, tutorías y talleres.',
    examples: ['Academias de idiomas', 'Clases de música', 'Talleres artísticos', 'Tutorías'],
    modules: [
      'reservas',
      'servicios',
      'profesionales',
      'recursos',
      'clientes',
      'pos',
      'finanzas',
      'automatizaciones',
      'reportes',
    ],
    addons: [
      'reservas.grupales',
      'servicios.paquetes',
      'servicios.membresias',
      'recursos.bloqueos',
    ],
    terms: {
      cita: 'Clase / Tutoría',
      citas: 'Clases',
      cliente: 'Alumno / Estudiante',
      clientes: 'Alumnos',
      profesional: 'Profesor / Instructor',
      profesionales: 'Profesores',
      servicio: 'Curso / Taller',
      servicios: 'Cursos',
      recurso: 'Aula / Laboratorio',
      recursos: 'Aulas y Laboratorios',
    },
  },

  profesional: {
    id: 'profesional',
    label: 'Servicios Profesionales',
    description: 'Despachos jurídicos, contables, consultorías de negocios y arquitectura.',
    examples: ['Abogados', 'Contadores', 'Consultores', 'Arquitectos', 'Asesores fiscales'],
    modules: [
      'reservas',
      'servicios',
      'profesionales',
      'recursos',
      'clientes',
      'finanzas',
      'automatizaciones',
      'reportes',
    ],
    addons: [
      'reservas.reprogramacion',
      'finanzas.cotizaciones',
      'recursos.bloqueos',
    ],
    terms: {
      cita: 'Reunión / Asesoría',
      citas: 'Reuniones',
      cliente: 'Cliente / Cuenta',
      clientes: 'Clientes',
      profesional: 'Consultor / Abogado',
      profesionales: 'Consultores',
      servicio: 'Asesoría / Proyecto',
      servicios: 'Servicios',
      recurso: 'Sala de Juntas',
      recursos: 'Salas de Juntas',
    },
  },

  creativo: {
    id: 'creativo',
    label: 'Estudios Creativos y Audiovisuales',
    description: 'Estudios de fotografía, producción de video, grabación musical y diseño.',
    examples: ['Estudios fotográficos', 'Productoras de video', 'Estudios de audio', 'Agencias'],
    modules: [
      'reservas',
      'servicios',
      'profesionales',
      'recursos',
      'clientes',
      'pos',
      'finanzas',
      'inventario',
      'reportes',
    ],
    addons: [
      'reservas.depositos',
      'recursos.bloqueos',
      'finanzas.cotizaciones',
    ],
    terms: {
      cita: 'Sesión / Rodaje',
      citas: 'Sesiones',
      cliente: 'Cliente / Productor',
      clientes: 'Clientes',
      profesional: 'Fotógrafo / Productor',
      profesionales: 'Creativos',
      servicio: 'Paquete de Sesión',
      servicios: 'Paquetes',
      recurso: 'Set / Estudio',
      recursos: 'Sets y Equipos',
    },
  },

  gastronomia: {
    id: 'gastronomia',
    label: 'Gastronomía y Hostelería',
    description: 'Restaurantes, cafeterías, bares, salones de té y reservas de mesas.',
    examples: ['Restaurantes', 'Cafeterías', 'Bares', 'Salones de té'],
    modules: [
      'reservas',
      'recepcion',
      'servicios',
      'recursos',
      'clientes',
      'pos',
      'finanzas',
      'inventario',
      'reportes',
    ],
    addons: [
      'recepcion.walk_in',
      'recepcion.lista_espera',
      'recursos.bloqueos',
      'pos.promociones',
    ],
    terms: {
      cita: 'Reserva de Mesa',
      citas: 'Reservas',
      cliente: 'Comensal',
      clientes: 'Comensales',
      profesional: 'Mesero / Chef',
      profesionales: 'Personal de Sala',
      servicio: 'Experiencia / Menú',
      servicios: 'Menús',
      recurso: 'Mesa / Zona',
      recursos: 'Mesas y Áreas',
    },
  },

  hogar: {
    id: 'hogar',
    label: 'Servicios a Domicilio y Técnicos',
    description: 'Reparaciones del hogar, plomería, electricidad, limpieza y mantenimiento.',
    examples: ['Plomería', 'Electricistas', 'Limpieza a domicilio', 'Cerrajería', 'Climatización'],
    modules: [
      'reservas',
      'servicios',
      'profesionales',
      'clientes',
      'pos',
      'finanzas',
      'inventario',
      'automatizaciones',
      'reportes',
    ],
    addons: [
      'reservas.domicilio',
      'finanzas.cotizaciones',
      'reservas.reprogramacion',
    ],
    terms: {
      cita: 'Visita Técnica',
      citas: 'Visitas',
      cliente: 'Cliente / Propietario',
      clientes: 'Clientes',
      profesional: 'Técnico Especialista',
      profesionales: 'Técnicos',
      servicio: 'Servicio / Instalación',
      servicios: 'Servicios',
      recurso: 'Vehículo / Herramienta',
      recursos: 'Vehículos y Equipos',
    },
  },

  mascotas: {
    id: 'mascotas',
    label: 'Mascotas y Veterinaria',
    description: 'Clínicas veterinarias, peluquería canina, adiestramiento y guarderías.',
    examples: ['Clínicas veterinarias', 'Grooming canino', 'Guarderías de mascotas', 'Adiestramiento'],
    modules: [
      'reservas',
      'recepcion',
      'servicios',
      'profesionales',
      'recursos',
      'clientes',
      'pos',
      'finanzas',
      'inventario',
      'automatizaciones',
      'reportes',
    ],
    addons: [
      'recepcion.walk_in',
      'recepcion.lista_espera',
      'recursos.bloqueos',
      'servicios.recetas',
    ],
    terms: {
      cita: 'Consulta / Cita',
      citas: 'Citas',
      cliente: 'Tutor / Dueño',
      clientes: 'Tutores',
      profesional: 'Veterinario / Groomer',
      profesionales: 'Especialistas',
      servicio: 'Atención / Baño',
      servicios: 'Servicios',
      recurso: 'Consultorio / Tina',
      recursos: 'Consultorios y Tinas',
    },
  },

  espacios: {
    id: 'espacios',
    label: 'Alquiler de Espacios e Inmuebles',
    description: 'Coworking, salones de eventos, canchas sintéticas, cabinas insonorizadas.',
    examples: ['Coworking', 'Salones de eventos', 'Canchas sintéticas', 'Estudios de ensayo'],
    modules: [
      'reservas',
      'servicios',
      'recursos',
      'clientes',
      'pos',
      'finanzas',
      'reportes',
    ],
    addons: [
      'recursos.bloqueos',
      'reservas.depositos',
      'servicios.membresias',
    ],
    terms: {
      cita: 'Reserva de Espacio',
      citas: 'Reservas',
      cliente: 'Arrendatario / Huésped',
      clientes: 'Clientes',
      profesional: 'Administrador',
      profesionales: 'Responsables',
      servicio: 'Tarifa / Plan de Uso',
      servicios: 'Tarifas',
      recurso: 'Espacio / Cancha',
      recursos: 'Espacios e Instalaciones',
    },
  },
}

export const ALL_INDUSTRIES = Object.values(INDUSTRY_PRESETS)

export function getIndustryPreset(id: IndustryId): IndustryPreset {
  return INDUSTRY_PRESETS[id] ?? INDUSTRY_PRESETS.general
}

export function translateTerm(
  industryId: IndustryId,
  key: TermKey,
  fallback: string,
  customTerms?: Partial<Record<TermKey, string>>
): string {
  if (customTerms && customTerms[key]) {
    return customTerms[key]!
  }
  const preset = getIndustryPreset(industryId)
  return preset.terms[key] ?? fallback
}
