import { TemaConfig } from '@/types'

export interface ThemePresetMeta {
  id: string
  name: string
  description: string
  category: string
  previewColors: string[]
  config: TemaConfig
}

export const THEME_PRESETS: Record<string, ThemePresetMeta> = {
  corporate: {
    id: 'corporate',
    name: 'Corporate',
    description: 'Estructurado, sobrio y altamente profesional para firmas y corporaciones.',
    category: 'Finanzas, Legal & Consultoría',
    previewColors: ['#1e3a8a', '#3b82f6', '#f8fafc'],
    config: {
      version: '1.0.0',
      presetName: 'Corporate',
      brand: {
        name: 'Nexus Corp',
        tagline: 'Soluciones estratégicas y servicios corporativos de alto nivel.',
        footerText: '© 2026 Nexus Corp. Todos los derechos reservados.',
        showPoweredBy: false,
        poweredByText: '',
        supportEmail: 'contacto@nexuscorp.com',
        supportPhone: '+1 555-0199',
        websiteUrl: 'https://nexuscorp.com',
        termsUrl: 'https://nexuscorp.com/terminos',
        privacyUrl: 'https://nexuscorp.com/privacidad',
      },
      colors: {
        primary: '#1e3a8a',
        primaryHover: '#172554',
        primarySoft: 'rgba(30, 58, 138, 0.12)',
        secondary: '#475569',
        accent: '#2563eb',
        success: '#10b981',
        warning: '#f59e0b',
        danger: '#ef4444',
        info: '#3b82f6',
        palettePredefinida: 'custom',
      },
      typography: {
        fontBody: 'Roboto',
        fontHeading: 'Montserrat',
      },
      radius: 'suave',
      shadows: 'subtle',
      density: 'compact',
      mode: 'light',
      assets: {
        logoUrl: '',
        logoDarkUrl: '',
        logoIconoUrl: '',
        faviconUrl: '',
      },
      whiteLabelActive: true,
      hideSystemBranding: true,
    },
  },

  modern: {
    id: 'modern',
    name: 'Modern',
    description: 'Dinámico, tecnológico y equilibrado para empresas SaaS y productos digitales.',
    category: 'Tecnología & SaaS',
    previewColors: ['#6366f1', '#818cf8', '#0f172a'],
    config: {
      version: '1.0.0',
      presetName: 'Modern',
      brand: {
        name: 'Aura Cloud',
        tagline: 'Plataforma inteligente de reservas y atención al cliente en tiempo real.',
        footerText: '© 2026 Aura Cloud Technologies Inc.',
        showPoweredBy: true,
        poweredByText: 'Powered by Aura Engine',
        supportEmail: 'soporte@auracloud.io',
        supportPhone: '+1 555-4080',
        websiteUrl: 'https://auracloud.io',
        termsUrl: 'https://auracloud.io/terms',
        privacyUrl: 'https://auracloud.io/privacy',
      },
      colors: {
        primary: '#6366f1',
        primaryHover: '#4f46e5',
        primarySoft: 'rgba(99, 102, 241, 0.12)',
        secondary: '#64748b',
        accent: '#8b5cf6',
        success: '#10b981',
        warning: '#f59e0b',
        danger: '#ef4444',
        info: '#3b82f6',
        palettePredefinida: 'indigo',
      },
      typography: {
        fontBody: 'Inter',
        fontHeading: 'Inter',
      },
      radius: 'moderno',
      shadows: 'elevated',
      density: 'comfortable',
      mode: 'system',
      assets: {
        logoUrl: '',
        logoDarkUrl: '',
        logoIconoUrl: '',
        faviconUrl: '',
      },
      whiteLabelActive: false,
      hideSystemBranding: false,
    },
  },

  elegant: {
    id: 'elegant',
    name: 'Elegant',
    description: 'Refinado, sofisticado y exclusivo para spas, estética y centros premium.',
    category: 'Belleza, Spa & Estética',
    previewColors: ['#8b5cf6', '#d946ef', '#18181b'],
    config: {
      version: '1.0.0',
      presetName: 'Elegant',
      brand: {
        name: 'Maison Luxe',
        tagline: 'Experiencias de bienestar, armonía estética y relajación exclusiva.',
        footerText: '© 2026 Maison Luxe Beauty & Spa.',
        showPoweredBy: false,
        poweredByText: '',
        supportEmail: 'concierge@maisonluxe.com',
        supportPhone: '+1 555-8899',
        websiteUrl: 'https://maisonluxe.com',
        termsUrl: 'https://maisonluxe.com/condiciones',
        privacyUrl: 'https://maisonluxe.com/privacidad',
      },
      colors: {
        primary: '#8b5cf6',
        primaryHover: '#7c3aed',
        primarySoft: 'rgba(139, 92, 246, 0.14)',
        secondary: '#71717a',
        accent: '#d946ef',
        success: '#10b981',
        warning: '#f59e0b',
        danger: '#ef4444',
        info: '#3b82f6',
        palettePredefinida: 'violet',
      },
      typography: {
        fontBody: 'Outfit',
        fontHeading: 'Outfit',
      },
      radius: 'suave',
      shadows: 'subtle',
      density: 'comfortable',
      mode: 'light',
      assets: {
        logoUrl: '',
        logoDarkUrl: '',
        logoIconoUrl: '',
        faviconUrl: '',
      },
      whiteLabelActive: true,
      hideSystemBranding: true,
    },
  },

  wellness: {
    id: 'wellness',
    name: 'Wellness',
    description: 'Natural, orgánico y sereno para bienestar, nutrición y terapias holísticas.',
    category: 'Salud, Nutrición & Bienestar',
    previewColors: ['#10b981', '#34d399', '#f0fdf4'],
    config: {
      version: '1.0.0',
      presetName: 'Wellness',
      brand: {
        name: 'Vitalis Vida',
        tagline: 'Cuidamos de ti con profesionales dedicados a tu salud integral.',
        footerText: '© 2026 Vitalis Vida Salud & Nutrición.',
        showPoweredBy: false,
        poweredByText: '',
        supportEmail: 'hola@vitalisvida.com',
        supportPhone: '+1 555-3210',
        websiteUrl: 'https://vitalisvida.com',
        termsUrl: 'https://vitalisvida.com/terminos',
        privacyUrl: 'https://vitalisvida.com/privacidad',
      },
      colors: {
        primary: '#10b981',
        primaryHover: '#059669',
        primarySoft: 'rgba(16, 185, 129, 0.12)',
        secondary: '#64748b',
        accent: '#14b8a6',
        success: '#10b981',
        warning: '#f59e0b',
        danger: '#ef4444',
        info: '#3b82f6',
        palettePredefinida: 'emerald',
      },
      typography: {
        fontBody: 'Poppins',
        fontHeading: 'Poppins',
      },
      radius: 'pronunciado',
      shadows: 'subtle',
      density: 'spacious',
      mode: 'light',
      assets: {
        logoUrl: '',
        logoDarkUrl: '',
        logoIconoUrl: '',
        faviconUrl: '',
      },
      whiteLabelActive: true,
      hideSystemBranding: true,
    },
  },

  medical: {
    id: 'medical',
    name: 'Medical',
    description: 'Clínico, confiable y de alta legibilidad para consultorios médicos y odontología.',
    category: 'Medicina, Clínicas & Odontología',
    previewColors: ['#0284c7', '#38bdf8', '#f8fafc'],
    config: {
      version: '1.0.0',
      presetName: 'Medical',
      brand: {
        name: 'Clínica San Gabriel',
        tagline: 'Atención médica especializada y citas presenciales o virtuales inmediatas.',
        footerText: '© 2026 Clínica San Gabriel. Centro Médico Acreditado.',
        showPoweredBy: false,
        poweredByText: '',
        supportEmail: 'citas@sangabriel.med',
        supportPhone: '+1 555-7000',
        websiteUrl: 'https://sangabriel.med',
        termsUrl: 'https://sangabriel.med/terminos',
        privacyUrl: 'https://sangabriel.med/privacidad',
      },
      colors: {
        primary: '#0284c7',
        primaryHover: '#0369a1',
        primarySoft: 'rgba(2, 132, 199, 0.12)',
        secondary: '#475569',
        accent: '#06b6d4',
        success: '#10b981',
        warning: '#f59e0b',
        danger: '#ef4444',
        info: '#0284c7',
        palettePredefinida: 'ocean',
      },
      typography: {
        fontBody: 'Roboto',
        fontHeading: 'Roboto',
      },
      radius: 'suave',
      shadows: 'subtle',
      density: 'compact',
      mode: 'light',
      assets: {
        logoUrl: '',
        logoDarkUrl: '',
        logoIconoUrl: '',
        faviconUrl: '',
      },
      whiteLabelActive: true,
      hideSystemBranding: true,
    },
  },

  minimal: {
    id: 'minimal',
    name: 'Minimal',
    description: 'Minimalista, geométrico y austero sin distracciones visuales ni sombras pesadas.',
    category: 'Estudios, Arquitectura & Diseño',
    previewColors: ['#334155', '#64748b', '#000000'],
    config: {
      version: '1.0.0',
      presetName: 'Minimal',
      brand: {
        name: 'Atelier Minimal',
        tagline: 'Diseño puro y gestión simplificada sin artificios.',
        footerText: '© 2026 Atelier Minimal.',
        showPoweredBy: false,
        poweredByText: '',
        supportEmail: 'studio@atelier.design',
        supportPhone: '+1 555-1100',
        websiteUrl: 'https://atelier.design',
        termsUrl: 'https://atelier.design/terms',
        privacyUrl: 'https://atelier.design/privacy',
      },
      colors: {
        primary: '#334155',
        primaryHover: '#1e293b',
        primarySoft: 'rgba(51, 65, 85, 0.12)',
        secondary: '#64748b',
        accent: '#475569',
        success: '#10b981',
        warning: '#f59e0b',
        danger: '#ef4444',
        info: '#3b82f6',
        palettePredefinida: 'slate',
      },
      typography: {
        fontBody: 'Inter',
        fontHeading: 'Inter',
      },
      radius: 'cuadrado',
      shadows: 'none',
      density: 'comfortable',
      mode: 'system',
      assets: {
        logoUrl: '',
        logoDarkUrl: '',
        logoIconoUrl: '',
        faviconUrl: '',
      },
      whiteLabelActive: true,
      hideSystemBranding: true,
    },
  },
}
